// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TMD.Controllers {
    public partial class AccountController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AccountController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AccountController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Logon() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Logon);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CompleteRegistration() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.CompleteRegistration);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CompletePasswordAssistance() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.CompletePasswordAssistance);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AccountController Actions { get { return Mvc.Account; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Account";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string AccountWidget = "AccountWidget";
            public readonly string LogOn = "LogOn";
            public readonly string Logon = "Logon";
            public readonly string Logout = "Logout";
            public readonly string Register = "Register";
            public readonly string CompleteRegistration = "CompleteRegistration";
            public readonly string PasswordAssistance = "PasswordAssistance";
            public readonly string CompletePasswordAssistance = "CompletePasswordAssistance";
            public readonly string Edit = "Edit";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string AccountWidget = "~/Views/Account/AccountWidget.cshtml";
            public readonly string CompletePasswordAssistance = "~/Views/Account/CompletePasswordAssistance.cshtml";
            public readonly string CompleteRegistration = "~/Views/Account/CompleteRegistration.cshtml";
            public readonly string Edit = "~/Views/Account/Edit.cshtml";
            public readonly string Logon = "~/Views/Account/Logon.cshtml";
            public readonly string PasswordAssistance = "~/Views/Account/PasswordAssistance.cshtml";
            public readonly string Register = "~/Views/Account/Register.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AccountController: TMD.Controllers.AccountController {
        public T4MVC_AccountController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult AccountWidget() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AccountWidget);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LogOn() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOn);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Logon(TMD.Models.AccountLogonModel model, bool captchaValid) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Logon);
            callInfo.RouteValueDictionary.Add("model", model);
            callInfo.RouteValueDictionary.Add("captchaValid", captchaValid);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Logout() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Logout);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Register() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Register);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Register(TMD.Model.IUnitOfWork uow, TMD.Models.AccountRegistrationModel model, bool captchaValid) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Register);
            callInfo.RouteValueDictionary.Add("uow", uow);
            callInfo.RouteValueDictionary.Add("model", model);
            callInfo.RouteValueDictionary.Add("captchaValid", captchaValid);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CompleteRegistration(TMD.Model.IUnitOfWork uow, string token) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CompleteRegistration);
            callInfo.RouteValueDictionary.Add("uow", uow);
            callInfo.RouteValueDictionary.Add("token", token);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PasswordAssistance() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PasswordAssistance);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PasswordAssistance(TMD.Model.IUnitOfWork uow, TMD.Models.AccountPasswordAssistanceModel model, bool captchaValid) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PasswordAssistance);
            callInfo.RouteValueDictionary.Add("uow", uow);
            callInfo.RouteValueDictionary.Add("model", model);
            callInfo.RouteValueDictionary.Add("captchaValid", captchaValid);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CompletePasswordAssistance(string token) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CompletePasswordAssistance);
            callInfo.RouteValueDictionary.Add("token", token);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CompletePasswordAssistance(TMD.Model.IUnitOfWork uow, TMD.Models.CompleteAccountPasswordAssistanceModel model, string token) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CompletePasswordAssistance);
            callInfo.RouteValueDictionary.Add("uow", uow);
            callInfo.RouteValueDictionary.Add("model", model);
            callInfo.RouteValueDictionary.Add("token", token);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(TMD.Model.IUnitOfWork uow, TMD.Models.AccountEditModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("uow", uow);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
