// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TMD.Controllers {
    public partial class BrowseController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BrowseController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected BrowseController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult MenuWidget() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.MenuWidget);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult TreeDetails() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.TreeDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult MeasurementDetails() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.MeasurementDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SiteDetails() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SiteDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SpeciesDetails() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SpeciesDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult StateDetails() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.StateDetails);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BrowseController Actions { get { return Mvc.Browse; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Browse";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string MenuWidget = "MenuWidget";
            public readonly string TreeDetails = "TreeDetails";
            public readonly string MeasurementDetails = "MeasurementDetails";
            public readonly string SiteDetails = "SiteDetails";
            public readonly string SpeciesDetails = "SpeciesDetails";
            public readonly string StateDetails = "StateDetails";
            public readonly string Species = "Species";
            public readonly string Locations = "Locations";
            public readonly string Index = "Index";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Locations = "~/Views/Browse/Locations.cshtml";
            public readonly string MenuWidget = "~/Views/Browse/MenuWidget.cshtml";
            public readonly string Species = "~/Views/Browse/Species.cshtml";
            public readonly string TreeDetails = "~/Views/Browse/TreeDetails.cshtml";
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string BrowsePhotoSumaryModel = "BrowsePhotoSumaryModel";
                public readonly string ConcatenatedNames = "ConcatenatedNames";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_BrowseController: TMD.Controllers.BrowseController {
        public T4MVC_BrowseController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult MenuWidget(bool isSelected) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.MenuWidget);
            callInfo.RouteValueDictionary.Add("isSelected", isSelected);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TreeDetails(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TreeDetails);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult MeasurementDetails(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.MeasurementDetails);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SiteDetails(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SiteDetails);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SpeciesDetails(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SpeciesDetails);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult StateDetails(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.StateDetails);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Species(int? page, string sort, bool? sortAsc, string botanicalNameFilter, string commonNameFilter) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Species);
            callInfo.RouteValueDictionary.Add("page", page);
            callInfo.RouteValueDictionary.Add("sort", sort);
            callInfo.RouteValueDictionary.Add("sortAsc", sortAsc);
            callInfo.RouteValueDictionary.Add("botanicalNameFilter", botanicalNameFilter);
            callInfo.RouteValueDictionary.Add("commonNameFilter", commonNameFilter);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Locations(int? page, string sort, bool? sortAsc, string stateFilter, string siteFilter, string subsiteFilter) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Locations);
            callInfo.RouteValueDictionary.Add("page", page);
            callInfo.RouteValueDictionary.Add("sort", sort);
            callInfo.RouteValueDictionary.Add("sortAsc", sortAsc);
            callInfo.RouteValueDictionary.Add("stateFilter", stateFilter);
            callInfo.RouteValueDictionary.Add("siteFilter", siteFilter);
            callInfo.RouteValueDictionary.Add("subsiteFilter", subsiteFilter);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index(int? speciesPage, string speciesSort, bool? speciesSortAsc, string speciesBotanicalNameFilter, string speciesCommonNameFilter, int? locationPage, string locationSort, bool? locationSortAsc, string locationStateFilter, string locationSiteFilter, string locationSubsiteFilter) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            callInfo.RouteValueDictionary.Add("speciesPage", speciesPage);
            callInfo.RouteValueDictionary.Add("speciesSort", speciesSort);
            callInfo.RouteValueDictionary.Add("speciesSortAsc", speciesSortAsc);
            callInfo.RouteValueDictionary.Add("speciesBotanicalNameFilter", speciesBotanicalNameFilter);
            callInfo.RouteValueDictionary.Add("speciesCommonNameFilter", speciesCommonNameFilter);
            callInfo.RouteValueDictionary.Add("locationPage", locationPage);
            callInfo.RouteValueDictionary.Add("locationSort", locationSort);
            callInfo.RouteValueDictionary.Add("locationSortAsc", locationSortAsc);
            callInfo.RouteValueDictionary.Add("locationStateFilter", locationStateFilter);
            callInfo.RouteValueDictionary.Add("locationSiteFilter", locationSiteFilter);
            callInfo.RouteValueDictionary.Add("locationSubsiteFilter", locationSubsiteFilter);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
