// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TMD.Controllers {
    public partial class ErrorController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ErrorController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ErrorController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult BypassBrowserCheck() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.BypassBrowserCheck);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ErrorController Actions { get { return Mvc.Error; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Error";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string NotFound = "NotFound";
            public readonly string ServerError = "ServerError";
            public readonly string IncompatibleBrowser = "IncompatibleBrowser";
            public readonly string BypassBrowserCheck = "BypassBrowserCheck";
            public readonly string Unauthorized = "Unauthorized";
            public readonly string Maintenance = "Maintenance";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string IncompatibleBrowser = "~/Views/Error/IncompatibleBrowser.cshtml";
            public readonly string Maintenance = "~/Views/Error/Maintenance.cshtml";
            public readonly string NotFound = "~/Views/Error/NotFound.cshtml";
            public readonly string ServerError = "~/Views/Error/ServerError.cshtml";
            public readonly string Unauthorized = "~/Views/Error/Unauthorized.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ErrorController: TMD.Controllers.ErrorController {
        public T4MVC_ErrorController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult NotFound() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.NotFound);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ServerError() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ServerError);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult IncompatibleBrowser() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.IncompatibleBrowser);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult BypassBrowserCheck(string ReturnUrl) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.BypassBrowserCheck);
            callInfo.RouteValueDictionary.Add("ReturnUrl", ReturnUrl);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Unauthorized() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Unauthorized);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Maintenance() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Maintenance);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
