// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TMD.Controllers {
    public partial class ExportController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ExportController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ExportController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Trees() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Trees);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Sites() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Sites);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SitesSpecies() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SitesSpecies);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult States() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.States);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult StatesSpecies() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.StatesSpecies);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Species() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Species);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SpeciesByFilters() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SpeciesByFilters);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult LocationsByFilters() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.LocationsByFilters);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ExportController Actions { get { return Mvc.Export; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Export";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Trees = "Trees";
            public readonly string Sites = "Sites";
            public readonly string SitesSpecies = "SitesSpecies";
            public readonly string States = "States";
            public readonly string StatesSpecies = "StatesSpecies";
            public readonly string Species = "Species";
            public readonly string SpeciesByFilters = "SpeciesByFilters";
            public readonly string LocationsByFilters = "LocationsByFilters";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ExportController: TMD.Controllers.ExportController {
        public T4MVC_ExportController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Trees(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Trees);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Sites(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Sites);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SitesSpecies(int id, string botanicalName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SitesSpecies);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("botanicalName", botanicalName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult States(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.States);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult StatesSpecies(int id, string botanicalName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.StatesSpecies);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("botanicalName", botanicalName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Species(string botanicalName, string commonName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Species);
            callInfo.RouteValueDictionary.Add("botanicalName", botanicalName);
            callInfo.RouteValueDictionary.Add("commonName", commonName);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SpeciesByFilters(string botanicalNameFilter, string commonNameFilter) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SpeciesByFilters);
            callInfo.RouteValueDictionary.Add("botanicalNameFilter", botanicalNameFilter);
            callInfo.RouteValueDictionary.Add("commonNameFilter", commonNameFilter);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LocationsByFilters(string stateFilter, string siteFilter, string subsiteFilter) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LocationsByFilters);
            callInfo.RouteValueDictionary.Add("stateFilter", stateFilter);
            callInfo.RouteValueDictionary.Add("siteFilter", siteFilter);
            callInfo.RouteValueDictionary.Add("subsiteFilter", subsiteFilter);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
