// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace TMD.Controllers {
    public partial class PhotosController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PhotosController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PhotosController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Caption() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Caption);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ViewPhoto() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ViewPhoto);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Remove() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Remove);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult PhotoAdded() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.PhotoAdded);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddToImportTree() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddToImportTree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddToImportSubsite() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddToImportSubsite);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PhotosController Actions { get { return Mvc.Photos; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Photos";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Caption = "Caption";
            public readonly string ViewPhoto = "View";
            public readonly string Remove = "Remove";
            public readonly string PhotoAdded = "PhotoAdded";
            public readonly string AddToImportTree = "AddToImportTree";
            public readonly string AddToImportSubsite = "AddToImportSubsite";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string CaptionPartial = "~/Views/Photos/CaptionPartial.cshtml";
            public readonly string EditPhotoGalleryPartial = "~/Views/Photos/EditPhotoGalleryPartial.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_PhotosController: TMD.Controllers.PhotosController {
        public T4MVC_PhotosController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Caption(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Caption);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ViewPhoto(int id, TMD.Model.Photos.PhotoSize size) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ViewPhoto);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("size", size);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Remove(TMD.Model.IUnitOfWork uow, int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Remove);
            callInfo.RouteValueDictionary.Add("uow", uow);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PhotoAdded(TMD.Models.PhotoGalleryModel gallery) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PhotoAdded);
            callInfo.RouteValueDictionary.Add("gallery", gallery);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddToImportTree(int id, int treeId, System.Web.HttpPostedFileBase imageData) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddToImportTree);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("treeId", treeId);
            callInfo.RouteValueDictionary.Add("imageData", imageData);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddToImportSubsite(int id, int subsiteId, System.Web.HttpPostedFileBase imageData) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddToImportSubsite);
            callInfo.RouteValueDictionary.Add("id", id);
            callInfo.RouteValueDictionary.Add("subsiteId", subsiteId);
            callInfo.RouteValueDictionary.Add("imageData", imageData);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
