// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string GoogleAnalyticsScript = "~/Views/Shared/GoogleAnalyticsScript.cshtml";
            public readonly string LoginLayout = "~/Views/Shared/LoginLayout.cshtml";
            public readonly string PrettyTimeSpan = "~/Views/Shared/PrettyTimeSpan.cshtml";
            public readonly string SiteLayout = "~/Views/Shared/SiteLayout.cshtml";
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string ConcatenatedNames = "ConcatenatedNames";
                public readonly string Coordinates = "Coordinates";
                public readonly string Country = "Country";
                public readonly string Distance = "Distance";
                public readonly string Elevation = "Elevation";
                public readonly string Enum = "Enum";
                public readonly string MapModel = "MapModel";
                public readonly string Name = "Name";
                public readonly string ObjectReport = "ObjectReport";
                public readonly string PhotoGalleryModel = "PhotoGalleryModel";
                public readonly string State = "State";
                public readonly string Volume = "Volume";
            }
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string Boolean = "Boolean";
                public readonly string CoordinatePickerModel = "CoordinatePickerModel";
                public readonly string Coordinates = "Coordinates";
                public readonly string DateTime = "DateTime";
                public readonly string Decimal = "Decimal";
                public readonly string Distance = "Distance";
                public readonly string Elevation = "Elevation";
                public readonly string Enum = "Enum";
                public readonly string MultilineText = "MultilineText";
                public readonly string Object = "Object";
                public readonly string Password = "Password";
                public readonly string PhotoGalleryModel = "PhotoGalleryModel";
                public readonly string State = "State";
                public readonly string String = "String";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
